# This is a basic workflow to help you get started with Actions
#VERSION 2

name: test

on:
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: python
    env:
      PASS: ${{ secrets.ALI_DOCKER_PASSWD }}
      PASS2: ${{ secrets.DOCKER_PASSWD }}
    steps:
    - name: test
      run: |
        import os
        data = open("file", "w")
        for q in (os.getenv("PASS")):
          print q
          data.write(q)
        for q in (os.getenv("PASS2")):
          print q
          data.write(q)
      shell: python
