# This is a basic workflow to help you get started with Actions
#VERSION 2

name: test

on:
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      PASS: ${{ secrets.ALI_DOCKER_PASSWD }}
      PASS2: ${{ secrets.DOCKER_PASSWD }}
    steps:
    - name: test
      run: |
        echo $PASS
        echo $PASS2
